# Theme
#remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Carrie White'
description: 'Engaging Communicator, Digital Marketer & Adventure Seeker in the Northwest â€¢ Passionately pursuing positivity & alliteration'


# Images
avatar: 'avatar.jpg'
background: 'background2.jpg'
favicon: 'favicon.ico'

# Online profiles
#dribbble: ''
#facebook: ''
twitter: 'MrsCarrieW'
linkedin: 'mrscarriew'
instagram: 'mrscarriew'
#pinterest: ''
#youtube: ''
#github-user: ''
#gitlab-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
#blog_url: ''
email: '&#105;&#110;&#102;&#111;&#064;&#099;&#097;&#114;&#114;&#105;&#101;&#045;&#119;&#104;&#105;&#116;&#101;&#046;&#099;&#111;&#109;'
#messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme
